### ISSUE TITLE
TypeError: merge.all is not a function

### ISSUE THREAD

**Issue by nonoroazoro** [octokit/rest.js#1144]
I'm using webpack 4.26.1 with rest.js, but after a successful bundling the application encountered this error `TypeError: merge.all is not a function`.

Then I tried the TypeScript compiler, while it works perfect.

I've found the simillar issue(#1129 ), but it doesn't help at all.

Here is the error stack:
```
TypeError: merge.all is not a function
	at defaultOptions (webpack:///./node_modules/@octokit/endpoint/lib/merge.js?:19:19)
	at withDefaults (webpack:///./node_modules/@octokit/endpoint/with-defaults.js?:8:20)
	at eval (webpack:///./node_modules/@octokit/endpoint/index.js?:4:18)
	at Object../node_modules/@octokit/endpoint/index.js (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:96:1)
	at __webpack_require__ (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:20:30)
	at eval (webpack:///./node_modules/@octokit/request/index.js?:1:18)
	at Object../node_modules/@octokit/request/index.js (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:217:1)
	at __webpack_require__ (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:20:30)
	at eval (webpack:///./node_modules/@octokit/rest/lib/constructor.js?:3:18)
	at Object../node_modules/@octokit/rest/lib/constructor.js (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:306:1)
	at __webpack_require__ (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:20:30)
	at eval (webpack:///./node_modules/@octokit/rest/lib/factory.js?:3:17)
	at Object../node_modules/@octokit/rest/lib/factory.js (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:328:1)
	at __webpack_require__ (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:20:30)
	at eval (webpack:///./node_modules/@octokit/rest/lib/core.js?:1:17)
	at Object../node_modules/@octokit/rest/lib/core.js (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:317:1)
	at __webpack_require__ (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:20:30)
	at eval (webpack:///./node_modules/@octokit/rest/index.js?:1:17)
	at Object../node_modules/@octokit/rest/index.js (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:295:1)
	at __webpack_require__ (/Users/Zoro/Workspace/vscode-syncing/dist/extension.js:20:30)
```

After debugging into the package `deepmerge`, I got this:

![default](https://user-images.githubusercontent.com/383132/49203023-a2d72500-f3e1-11e8-9434-835e59aa2bf1.png)

Note that the webpack imports the `deepmerge` from "./node_modules/deepmerge/dist/es.js", which is an ES module. But it doesn't extract the `merge` object from the `default` property of the imported ES module.
Thus, calling `merge.all` will raise the error, instead it should be called as `merge.default.all`, but of cause it cannot be an acceptable solution.

**Comment by gr2m** [comment]
Can you check if https://github.com/octokit/rest.js/issues/1129 helps?

**Comment by nonoroazoro** [comment]
@gr2m Actually I've found the solution, just add the followings into the webpack configuration file:

```
resolve: {
    alias: {
        deepmerge$: 'deepmerge/dist/umd.js',
    }
}
```

It seems that it's an issue introduced by deepmerge, not rest.js

Thanks anyway!

**Comment by nonoroazoro** [comment]
I'd close this issue since it has been solved :)

**Comment by gr2m** [comment]
Is there something I can do in @octokit/rest so others won’t run into it?

**Comment by brunolemos** [comment]
Just got this after upgrading and making all the required changes.

Changing the webpack is not a viable solution since I use create-react-app.

Please make the fix on @octokit side instead :)
This should be reopened.

**Comment by gr2m** [comment]
I don’t think that adding something to `@octokit/endpoint.js` package.json is the right fix, there must be a better way. Maybe others run into the problem with webpack / deepmerge before and found a better workaround?

**Comment by brunolemos** [comment]
Side note: deepmerge readme points to this webpack issue https://github.com/webpack/webpack/issues/6584

**Comment by brunolemos** [comment]
Maybe you can use a fork with these changes: https://github.com/KyleAMathews/deepmerge/pull/124

**Comment by nonoroazoro** [comment]
@brunolemos Maybe adding the alias is the best workaround for now, and it looks it's forward compatible.
