### ISSUE TITLE
Cannot read property 'replace' of undefined at restEndpoint 

### ISSUE THREAD

**Issue by himanshu219** [octokit/rest.js#1620]
I am using probot framework and and am running it on AWS Lambda.
For event = "installation_repositories.added" I am getting below error

```
2020-02-20T12:24:01.320Z 6f69b99c-caa8-4999-842d-d1ce5c375704 ERROR TypeError: Cannot read property 'replace' of undefined at restEndpoint (/opt/nodejs/node_modules/@octokit/rest/lib/endpoint/index.js:43:13) at restRequest (/opt/nodejs/node_modules/@octokit/rest/lib/request/index.js:7:26)
```

Here's the code snippet and I am following these docs https://octokit.github.io/rest.js/#octokit-routes-repos-update-branch-protection

```
        const owner = context.payload.installation.account.login;
        context.payload.repositories_added.forEach(async (repository) => {

            const repo = repository.name;
            const response = await context.github.repos.updateBranchProtection({
                owner,
                repo,
                branch: "master",
                required_status_checks: {
                "strict": true,
                "contexts": [
                  "CI/CD:Unit Tests",
                  "CI/CD:API Tests",
                  "CI/CD:UI Tests"
                ]
                },
                enforce_admins: true,
                required_pull_request_reviews: {
                    "require_code_owner_reviews": true,
                    "required_approving_review_count": 1,
                 },
                restrictions: null,
            }).catch((err) => console.error(err));        
        });
```

After digging into the code It seems that it is not getting url. Am I missing something here? What scenarios could be possible to throw the above error.

**Comment by gr2m** [comment]
Can you please make sure you are using the latest version of `@octokit/rest`? You can find out your current version with `npm ls @octokit/rest`

If the problem persists, can you try to isolate the error by just using `@octokit/rest` without Probot? Note that I'll probably release v17 of `@ocotkit/rest` today, so make sure you test with the last v16 version. Ideal would be a reproducible test case on runkit.com, like https://runkit.com/gr2m/octokit-rest-js-1553
