### ISSUE TITLE
improve ESM compatibility by using fully qualified file names with extension

### ISSUE THREAD

**Issue by arlac77** [octokit/rest.js#1623]
On the long journey to native ESM modules (for all engines) one step would be the use of
fully qualified imports (with .js | .mjs extension)

```js
import { VERSION } from "./version.mjs";
```

any opinions ?

**Comment by gr2m** [comment]
The published package.json has the `"module"` key

```json
  "module": "dist-web/index.js"
```

So the `.mjs` extension is not necessary. It should just work, did you try it?

**Comment by wolfy1339** [comment]
Might want to look at this TypeScript issue where they discuss adding file extensions to import statements: https://github.com/microsoft/TypeScript/issues/16577

**Comment by arlac77** [comment]
Starting with version 17.0.0 i am having difficulties to use plugins (here throttling).
Probably have to go using "@octokit/core" directly.
Thereby i saw the following statement
```js
import { VERSION } from "./version"; // without .js | .mjs
```
which does not work natively on node (see [enabling esm](https://nodejs.org/dist/latest-v13.x/docs/api/esm.html#esm_enabling))

As far as i know the package.json "module" key is only used by bundlers not node itself

**Comment by wolfy1339** [comment]
What kind of issues are you having? There's a bug where you can't use an Array of plugins, instead you have to add them one by one

**Comment by gr2m** [comment]
> As far as i know the package.json "module" key is only used by bundlers not node itself

Yes you are right, sorry it was a long day. Note that the source code in this repository is not what is published to npm, there is a build step using [`@pika/pack`](https://github.com/pikapkg/builders), which is just a set of rollup plugins. So adding native support for Node's ESM system is just a matter of the build system, not the source code. And I know for a fact that the Pika folks have been very involved in Node's ESM working group, I'm sure it is something they are looking actively into.

I've added native Node ESM support to my backlog, together with native support for Deno, Electron, React Native and other common JavaScript/TypeScript runtime environments

**Comment by arlac77** [comment]
> What kind of issues are you having? There's a bug where you can't use an Array of plugins, instead you have to add them one by one

running against raw node 13:

TypeError: _octokit.plugin_ is not a function
when using version 17.0.0 (worked before 16.4x.y)

´´´js
import octokit from "@octokit/rest";
import throttling from "@octokit/plugin-throttling";
...
const oc = octokit.plugin(throttling.throttling)({ // TypeError: octokit.plugin is not a function (raw node 13}
throttle: {
...
});
´´´

**Comment by wolfy1339** [comment]
That's because you haven't followed the migration guide from v16 to v17. We switched to using named exports.

```js
import { Octokit } from "@octokit/rest";
import { throttling } from "@octokit/plugin-throttling";
// You could also use the same import as in your code snippet

const oc = Octokit.plugin(throttling)({
    throttle: {
        [...]
    }
});
```

**Comment by arlac77** [comment]
> That's because you haven't followed the migration guide from v16 to v17. We switched to using named exports.
> 
> ```js
> import { Octokit } from "@octokit/rest";
> import { throttling } from "@octokit/plugin-throttling";
> // You could also use the same import as in your code snippet
> 
> const oc = new Octokit.plugin(throttling)({
>     throttle: {
>         [...]
>     }
> });
> ```

Sorry but that does not work for me (node 13.8.0):

```sh
  import { Octokit } from "@octokit/rest";
           ^^^^^^^
  SyntaxError: The requested module '@octokit/rest' does not provide an export named 'Octokit'
```

**Comment by wolfy1339** [comment]
Can you try using `@octokit/rest/dist-web/index.js` or `@octokit/rest/dist-src/index.js`?

**Comment by arlac77** [comment]
Same outcome for all three variants

[arlac77/octokit-esm-problem/](https://github.com/arlac77/octokit-esm-problem)

```sh
$ node index-rest.mjs 
(node:16483) ExperimentalWarning: The ESM module loader is experimental.
file:///Users/markus/build/octokit-esm-problem/index-rest.mjs:1
import { Octokit } from "@octokit/rest";
         ^^^^^^^
SyntaxError: The requested module '@octokit/rest' does not provide an export named 'Octokit'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:164:24)
$ node index-rest-dist-src.mjs 
(node:16484) ExperimentalWarning: The ESM module loader is experimental.
file:///Users/markus/build/octokit-esm-problem/index-rest-dist-src.mjs:1
import { Octokit } from "@octokit/rest/dist-src/index.js";
         ^^^^^^^
SyntaxError: The requested module '@octokit/rest/dist-src/index.js' does not provide an export named 'Octokit'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:164:24)
$ node index-rest-dist-web.mjs 
(node:16485) ExperimentalWarning: The ESM module loader is experimental.
file:///Users/markus/build/octokit-esm-problem/index-rest-dist-web.mjs:1
import { Octokit } from "@octokit/rest/dist-web/index.js";
         ^^^^^^^
SyntaxError: The requested module '@octokit/rest/dist-web/index.js' does not provide an export named 'Octokit'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:164:24)
$ node --version
v13.8.0
```

**Comment by wolfy1339** [comment]
What happens if you try the default import and access the `Octokit` property?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by arlac77** [comment]
```js
import  Octokit  from "@octokit/rest";
```

$ node index-rest.mjs 
(node:16657) ExperimentalWarning: The ESM module loader is experimental.
{ Octokit: [Function: OctokitWithDefaults] }

**Comment by wolfy1339** [comment]
It seems ESM named import doesn't work with the module.

In your case, just use
```js
import Octokit from "@octokit/rest";
import throttling from "@octokit/plugin-throttling"

const oc = new Octokit.Octokit.plugin(throttling)({
    [...]
});
```

@gr2m This should probably be noted on the docs somewhere for users that use ESM

**Comment by gr2m** [comment]
Hmm yeah I'll have to think about it. I'm not sure if there is a [`@pika/pack`](https://github.com/pikapkg/builders) plugin for Node's ESM support yet. I know the Pika folks are looking into the new `"exports"` key of package.json, I don't know what their status is

**Comment by arlac77** [comment]
My intention only was to move into the future where ESM is the new normal for all engines (and bundlers and special tweaking with "exports" are optional).
I will stick with the older (working!) version until you have decided where to go

**Comment by wolfy1339** [comment]
You can definitely use v17 with ESM, though you won't be able to benefit from named exports.
You'll have to use the `Octokit` property of the default export
```js
import octokit from "@octokit/rest";
const Octokit = Octokit.Octokit;
// Rest of code uses Octokit variable just like in v16.
```
________________________________

**Comment by oscar6echo** [comment]
I confirm the solution provided by @wolfy1339  works for me:

```js
// test.mjs
import rest from "@octokit/rest";
const octokit = new rest.Octokit();
console.log(rest);
```
`node test.mjs` outputs:

```js
{ Octokit: [Function: OctokitWithDefaults] }
```

Strange. Probably because ESM are still experimental.  
After this initial subtlety, all seems to work fine.

**Comment by arlac77** [comment]
What about adding [babel-plugin-transform-require-extensions](https://github.com/jaydenseric/babel-plugin-transform-require-extensions) to the build pipeline and always generate *.mjs ?

See similar uses with graphql-js [Export clean ESM modules](https://github.com/graphql/graphql-js/issues/1819)

**Comment by wolfy1339** [comment]
The problem with that is that we use TypeScript and the pika build system. Our configuration doesn't use babel to compile the TypeScript

**Comment by arlac77** [comment]
@wolfy1339 

The pika node builder us using @babel
[plugin-build-node](https://github.com/pikapkg/builders/blob/master/packages/plugin-build-node/package.json)
```json
    "@babel/core": "^7.0.0",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/plugin-syntax-import-meta": "^7.2.0",
    "@babel/preset-env": "^7.2.3",
    "@pika/types": "^0.9.2",
```

**Comment by wolfy1339** [comment]
Indeed it is. But, there is currently no way to use a custom babelrc file or pass custom babel plugins.

And there is no pika builder for ESM yet
