### ISSUE TITLE
[BUG]: Creating deployments fail with "Request body length does not match content-length header"

### ISSUE THREAD

**Issue by NiklasMerz** [octokit/rest.js#405]
### What happened?

I updated my very old octokit and nodejs version to the most recent ones and **creating deployments** now fails.

Any ideas what should I try?

Some code:
```js
let options = {
  auto_merge: false,
  owner: 'myorga',
  repo: 'myproject',
  ref: 'develop',
  environment: 'testing'
}

async function createDeployment(options) {
    options.task = 'deploy';
    options.required_contexts = [];
    let result = await octokit.rest.repos.createDeployment(options)
    const id = result.data.id;
    console.log(id);
    fs.writeFileSync(process.env.HOME + '/deployment_action', id);
    
    console.log(result.status == 201 ? 'Done': 'Error');
    if(result.status != 201) {
        console.error(result);
        process.exit(1);
    }
}
```

### Versions

octokit-rest.js/20.0.2
octokit-core.js/5.1.0
Node.js/18.19.0 (linux; x64)',

### Relevant log output

```shell
/node_modules/@octokit/request/dist-node/index.js:156
    throw new import_request_error.RequestError(message, 500, {
          ^

RequestError [HttpError]: Request body length does not match content-length header
    at /node_modules/@octokit/request/dist-node/index.js:156:11
    at async createDeployment (/usr/bin/deployment.js:13:18) {
  status: 500,
  request: {
    method: 'POST',
    url: 'https://api.github.com/repos/pragmaticindustries/ukonn-wizard/deployments',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/20.0.2 octokit-core.js/5.1.0 Node.js/18.19.0 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"auto_merge":false,"ref":"develop","environment":"testing","task":"deploy","required_contexts":[]}',
    request: { hook: [Function: bound bound register] }
  }
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by NiklasMerz** [comment]
After finding this issue https://github.com/semantic-release/github/issues/746 I realized we renamed the repo and the workflow used the old name. Strange error but this fixes it.

**Comment by wolfy1339** [comment]
Maybe this warrants a mention in the docs? Or maybe there is a fix that we can do on our side to avoid the error

**Comment by ptr-h** [comment]
I am having the same error, when I add permission: "pull" to the add collaborators call. I have tried two ways to add and am seeing the same error:
```
RequestError [HttpError]: Request body length does not match content-length header
    at eval (webpack-internal:///(rsc)/./node_modules/@octokit/request/dist-src/fetch-wrapper.js:108:15)
    at async addCollaborator (webpack-internal:///(rsc)/./src/app/library/functions/products/add-collaborator.ts:9:9)
    at async POST (webpack-internal:///(rsc)/./src/app/api/product/get-github-access/route.ts:38:17)

  status: 500,
  request: {
    method: 'PUT',
    url: 'https://api.github.com/repo/owner/repo_name/collaborators/github_username',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/20.0.2 octokit-core.js/5.0.2 Node.js/18.18.2 (darwin; arm64)',
      'x-github-api-version': '2022-11-28',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"permission":"pull"}',
    request: { hook: [Function: bound bound register] }
  }
}

```
Method 1:
```
        await octokit.repos.addCollaborator({
            owner: 'yourfirstsaas',
            repo: "template",
            username: githubUsername,
            permission: 'pull',
        });
```

Method 2:
```
        await octokit.request(`PUT /repos/owner/repo/collaborators/${githubUsername}`, {
            owner: 'owner',
            repo: 'repo_name',
            username: githubUsername,
            permission: 'pull',
```

the same whether I add header or not:
```
            headers: {
              'X-GitHub-Api-Version': '2022-11-28'
            }

```
