### ISSUE TITLE
[DOCS]: errors in the console, search doesn't work

### ISSUE THREAD

**Issue by dimaqq** [octokit/rest.js#433]
### Describe the need

I'm unable to use search at https://octokit.github.io/rest.js/v20

There are also following errors in the console:

![Screenshot 2024-05-23 at 13 50 13](https://github.com/octokit/rest.js/assets/662249/52d32eeb-e4e3-44cb-be56-f0af6629981b)

```
production-app.js:283 TypeError: x is not a function
    at n.render (endpoint.js:44:10)
    at Ho (react-dom.production.min.js:187:188)
    at $o (react-dom.production.min.js:186:173)
    at Ku (react-dom.production.min.js:269:427)
    at Li (react-dom.production.min.js:250:347)
    at Ni (react-dom.production.min.js:250:278)
    at Pi (react-dom.production.min.js:250:138)
    at bi (react-dom.production.min.js:243:163)
    at hi (react-dom.production.min.js:237:175)
    at Ji (react-dom.production.min.js:285:27)
```

### SDK Version

v20

### Relevant log output

```shell
production-app.js:283 TypeError: x is not a function
    at n.render (endpoint.js:44:10)
    at Ho (react-dom.production.min.js:187:188)
    at $o (react-dom.production.min.js:186:173)
    at Ku (react-dom.production.min.js:269:427)
    at Li (react-dom.production.min.js:250:347)
    at Ni (react-dom.production.min.js:250:278)
    at Pi (react-dom.production.min.js:250:138)
    at bi (react-dom.production.min.js:243:163)
    at hi (react-dom.production.min.js:237:175)
    at Ji (react-dom.production.min.js:285:27)
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hunxjunedo** [comment]
@dimaqq kindly assign this issue to me.

**Comment by gr2m** [comment]
All yours @hunxjunedo 👍 Thanks for looking into it

**Comment by hunxjunedo** [comment]
it's weird that the search is working absolutely fine on my system, however I noticed a small difference, the live version doesn't show the favicon, while the local one does. Will take some time identifying the problem

**Comment by hunxjunedo** [comment]
I'm pretty sure an issue of this type is not new in this repo, the disabled menu button despite the complete functionality in code clearly shows that it was once written to work, but was disabled due to the exact same problem with Gatsby. Now we have to decide the severity of this issue: do we need to migrate from Gatsby or just leave it as it is.

**Comment by gr2m** [comment]
I assume that problem existed for a long while. And `@octokit/rest` is an Octokit SDK variant that exists for legacy reasons. We recommend to use https://github.com/octokit/octokit.js instead. All this to say, this is not urgent.

**Comment by hunxjunedo** [comment]
Will be happy contribute to the new docs, just lemme know when you guys are looking to do it, this can be done in really simpler way other than Gatsby. Today was real hectic.

**Comment by wolfy1339** [comment]
Feel free to contribute to a new docs page. There isn't a set timeline

**Comment by AbandonedCart** [comment]
> I assume that problem existed for a long while. And `@octokit/rest` is an Octokit SDK variant that exists for legacy reasons. We recommend to use https://github.com/octokit/octokit.js instead. All this to say, this is not urgent. I also think that Gatsby is overkill for this documentation page

I'd like to make a counterpoint to this. I forked a project that was using this instead of the newer version you linked. Unfortunately, I am unable to search in the documentation to make sure I understand what they were trying to accomplish before hastily attempting to rewrite it. The documentation of an obsolete project is perhaps the **most** important thing to leave in a working state.

**Comment by hunxjunedo** [comment]
Yeah it has been understood and acknowledged, and I intend to release a functional and better version of the docs soon Inshallah.

**Comment by wolfy1339** [comment]
> I'd like to make a counterpoint to this. I forked a project that was using this instead of the newer version you linked. 

`@octokit/rest` is still being updated, and the same endpoints are available in `octokit`. The only difference is that the endpoints methods are prefixed with `rest.` in the `octokit` package, while here they are available both unprefixed and prefixed.

 If you only need the REST endpoints, then this is much more minimal then octokit.

**Comment by AbandonedCart** [comment]
> `@octokit/rest` is still being updated, and the same endpoints are available in `octokit`. The only difference is that the endpoints methods are prefixed with `rest.` in the `octokit` package, while here they are available both unprefixed and prefixed.
> 
> If you only need the REST endpoints, then this is much more minimal then octokit.

Unfortunately, what I needed was to know was about the code I ended up with that already made that decision. I found my answers, but it was a needlessly tedious process that deterred me from bothering with a change at that point.

**Comment by wolfy1339** [comment]
@hunxjunedo Have you made any progress on this issue?

**Comment by hunxjunedo** [comment]
Not yet, really busy nowadays, will prolly do it this month.
